name: clothing_ecommerce
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.2
  connectivity_plus: ^2.2.0
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  location: ^4.4.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  provider: ^6.0.1
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  vertical_scrollable_tabview: ^0.0.7
  khalti_flutter: ^2.1.0
  fluttertoast: ^8.1.2
  otp_text_field: ^1.1.3
  extended_phone_number_input: ^1.0.2
  flutter_stripe: ^7.0.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/auth/

  # fonts:
  # - family: Poppins
  #   fonts:
  #     - asset: assets/fonts/Poppins/Poppins-Thin.ttf
  #       weight: 200
  #     - asset: assets/fonts/Poppins/Poppins-Light.ttf
  #       weight: 300
  #     - asset: assets/fonts/Poppins/Poppins-Regular.ttf
  #       weight: 400
  #     - asset: assets/fonts/Poppins/Poppins-Medium.ttf
  #       weight: 500
  #     - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
  #       weight: 600
  #     - asset: assets/fonts/Poppins/Poppins-Bold.ttf
  #       weight: 700
  #     - asset: assets/fonts/Poppins/Poppins-Black.ttf
  #       weight: 800
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
